### PR TITLE
Initial refactor of the main mod class code.

### PR DESCRIPTION
**Pull request by KrisToe4**
Main Changes:
- Updated project and new solution files for Visual Studios 2017 Community
- Break out major portions of UI logic into helper functions
- Pre-configure data in rough db-like way to reduce code duplication

### CODE REVIEW

**Comment by KrisToe4** [comment]
I'm just dipping my toes into modding Terraria and summoners are my true-calling. I found your mod and am planning on building my own summoner mod but I wanted to give you a bit of help with your mod first.  

The changes look bigger than they really are because of a file rename, its mostly the same just shuffled around a little. The biggest change involves the dictionary defined at the top. I'm going to be making some further adjustments to my fork and you're free to take whatever you like and merge it into your main branch.

**Comment by JavidPack** [comment]
Thanks, I'll look over this later, in a few days. I'm still a little disappointed with this mod, I was was never able to put any time into it to make the mod complete and make a pure summoner play style enjoyable. 

This mod is consistently downloaded a lot, top 30 most days. (100k downloads so far) If you'd like to continue contributing, maybe our visions overlap enough that you can continue implementing things while benefiting from the already huge install base. Just a thought. If not, I'm appreciative for your code contributions so far, it's really nice to have contributions.

**Comment by JavidPack** [comment]
Ok, I merged your changes, but it went through another branch/PR because I tried to edit some of your changes. So I'll close this now. I'll be publishing an update in a bit after I check it

**Comment by KrisToe4** [comment]
Hey there, sorry I didn't notice you'd posted a message on this. 

I'm not sure yet how much time I'm going to have to actually start doing terraria modding but if I find the time I'll let you know and I think we can work something out. I'm more than happy to share my development experience with you.

**Pull request closed without merging**
